# The radius to consider for clusters; the clusters themselves may extend outside this radius.
grow-radius: 20

# Controls the probability a given spot inside the grow_radius will be chosen as a cluster center.
cluster-factor:
  kelp: 2
  seagrass: 15

# The maximum radius for clusters. Each cluster will be a random size up to this value.
cluster-radius:
  kelp: 10
  seagrass: 6

# Average density of each cluster.
cluster-density:
  kelp: 25
  seagrass: 90
  
grow-blocks:
  - "minecraft:sand"
  - "minecraft:gravel"
  - "minecraft:dirt"
  - "minecraft:clay"