# The radius to consider for clusters; the clusters themselves may extend outside this radius.
grow-radius: 20

# Controls the probability a given spot inside the grow_radius will be chosen as a cluster center.
cluster-factor:
  kelp: 5
  seagrass: 12

# The maximum radius for clusters. Each cluster will be a random size up to this value.
cluster-radius:
  kelp: 6
  seagrass: 4

# Average density of each cluster.
cluster-density:
  kelp: 35
  seagrass: 60

# A list of blocks that kelp and seagrass can grow on
# Must be a string in standard Minecraft ID format
grow-blocks:
  - "minecraft:sand"
  - "minecraft:gravel"
  - "minecraft:dirt"
  - "minecraft:clay"

# A list of biomes that kelp and seagrass will grow in
# Must be a string in standard Minecraft ID format
grow-biomes:
  - "minecraft:ocean"
  - "minecraft:deep_ocean"