# The radius to consider for clusters; the clusters themselves may extend outside this radius.
grow_radius: 100

# Controls the probability a given spot inside the grow_radius will be chosen as a cluster center.
cluster_factor:
  kelp: 4
  seagrass: 12

# The maximum radius for clusters. Each cluster will be a random size up to this value.
cluster_radius:
  kelp: 8
  seagrass: 6

# Average density of each cluster.
cluster_density:
  kelp: 15
  seagrass: 90