name: OceanGrow
main: com.minefit.xerxestireiron.oceangrow.OceanGrow
version: 0.9.3
author: XerxesTireIron
description: Allows use of a wand to grow kelp and seagrass in oceans
load: postworld
api-version: 1.13

commands:
    oceangrow:
        description: 'Commands for OceanGrow'
        usage: /oceangrow <reload/kelp-wand/seagrass-wand>
permissions:
    oceangrow.*:
        description: Full access to OceanGrow commands
        children:
            oceangrow.usewand: true
            oceangrow.reload: true
        oceangrow.usewand:
            description: Can use the wand
            default: op
        oceangrow.reload:
            description: Can reload OceanGrow configuration
            default: op